os: osx
language: go
go:
- 1.9
addons:
  ssh_known_hosts: 182.92.79.110
before_install:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
script:
  - GOARCH=amd64 GOOS=linux go build -o main *.go
deploy:
  provider: script
  script:
  - scp -o StrictHostKeyChecking=no ./main root@182.92.79.110:~/golang/
  - scp -o StrictHostKeyChecking=no ./conf.yaml root@182.92.79.110:~/golang/
  - bash ./deploy.sh
  # script: echo 'Here you go'
  skip_cleanup: true
branches:
  only: 
    - master